version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_DB: warehouse_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raf
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: